### ISSUE TITLE
My Total XXX Value needs to be dynamically updated

### ISSUE THREAD

**Issue by edchiou** [TeamStacks/hw4#1]
'My Total Coin Value', 'My Total Gold Value', etc. should all be updated from the Inventory database.

**Comment by angien** [comment]
use parse query and total the total column

**Comment by jiaj0000** [comment]
as well as the daily and overall

![2015-06-05 9 09 39](https://cloud.githubusercontent.com/assets/7988574/8018269/438b69a4-0bc7-11e5-9328-0d72c1658b72.png)
