### ISSUE TITLE
Set up build task

### ISSUE THREAD

**Issue by whleung** [TeamStacks/hw4#11]
> 10pts for build process and distribution version
> 
> Since you are going to stop working on this app you must make sure it is ready for distribution and handoff. For distribution you must make sure you can use a build task (you may find Grunt or Gulp useful) to minify your CSS and JS and even your HTML if you like. You should also make sure that your files are bundled together into a minimum number of files. You must turn in a repo or zip file that contains both the production and development version of your app.

**Comment by jiaj0000** [comment]
I dont see this in the new reduced requirement... It will be counted towards extra credit.

https://groups.google.com/forum/#!topic/ucsd-cse-134b-spring-2015/McHAEmBQDwQ
